name: "Hello Actions sample2"
description: "Greet someone"
author: "test@github.com"

inputs:
  MY_NAME: 
    description: "Who to greet"
    required: true
    default: "World"
    
runs: 
  using: "docker"
  image: "Dockerfile"
  
branding:
  icon: "mic"
  color: "purple"
